-- 🔹 Basic Aggregation Questions

-- 1. What is the total number of orders placed?
SELECT SUM(total)
FROM public.orders

-- 2. What is the total revenue (total_amt_usd) across all orders?
SELECT SUM(total_amt_usd)
FROM public.orders

-- 3. What is the average order value?
SELECT AVG(total)
FROM public.orders

/*
4. What is the total quantity sold for:
	o standard paper?
	o poster paper?
	o glossy paper?
*/

SELECT SUM(standard_qty)
FROM public.orders

SELECT SUM(poster_qty)
FROM public.orders

SELECT SUM(gloss_qty)
FROM public.orders

-- 5. What is the highest single order amount?
SELECT MAX(total_amt_usd)
FROM public.orders

-- 🔹 Aggregations with GROUP BY (Single Table)

-- 6. What is the total revenue generated by each account_id?
SELECT SUM(total_amt_usd)
FROM public.orders
GROUP BY account_id

-- 7. How many orders has each account placed?
SELECT COUNT(account_id)
FROM public.orders
GROUP BY account_id

-- 8. What is the average order value per account?
SELECT AVG(total_amt_usd)
FROM public.orders
GROUP BY account_id

-- 9. What is the total revenue per year (based on orders.occurred_at)? 
/* 
EXTRACT is a function used to retrieve information of a field from a source
EXTRACT (field FROM source)
*/
SELECT 
	EXTRACT(year FROM occurred_at) as year,
	SUM(total_amt_usd) as total_revenue
FROM public.orders
GROUP BY year

-- 10. What is the total revenue per month?

SELECT 
	EXTRACT(year FROM occurred_at) as year,
	EXTRACT(month FROM occurred_at) as month,
	SUM(total_amt_usd) as total_revenue
FROM public.orders
GROUP BY year,month 

-- 🔹 Multi-Table Aggregations (JOIN + GROUP BY)

-- 11. What is the total revenue generated by each account (accounts.name)?
SELECT
	acc.name acc_names,
	SUM(total_amt_usd) total_revenue
FROM public.orders odd
LEFT JOIN public.accounts acc
ON odd.account_id = acc.id
GROUP BY name 

-- 12. What is the total revenue generated by each sales rep?

-- (orders ➡️ accounts ➡️ sales_reps)
SELECT 
	reps.name reps_names,
	SUM(total_amt_usd) revenue 
FROM public.orders odd
LEFT JOIN public.accounts acc
	ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps
	ON reps.id = acc.sales_rep_id
GROUP BY reps_names
ORDER BY revenue DESC                        -- To group reps from top perfomers going down

-- Above query followed the chain (orders ➡️ accounts ➡️ sales_reps)

-- 13. How many orders has each sales rep handled?
SELECT 
	reps.name representatives_names,
	COUNT(total) orders_handled 
FROM public.orders odd 
LEFT JOIN public.accounts acc 
ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps
ON reps.id = acc.sales_rep_id
GROUP BY reps.name
ORDER BY orders_handled DESC                       -- To see reps perfomance from high - low. 

-- 14. What is the total revenue generated in each region?

-- (orders ➡️ accounts ➡️ sales_reps ➡️ region)
SELECT 
	reg.name region_name,
	SUM(total_amt_usd) total_revenue
FROM public.orders odd
LEFT JOIN public.accounts acc
	ON odd.account_id = acc.id 
LEFT JOIN public.sales_reps reps
	ON reps.id = acc.sales_rep_id
LEFT JOIN public.region reg
	ON reg.id = reps.region_id
GROUP BY reg.name 
ORDER BY total_revenue DESC

-- 15. What is the average order value per region?

-- (orders ➡️ accounts ➡️ sales_reps ➡️ region)
SELECT 
	reg.name region_name,
	ROUND(AVG(total), 2) average_order_value
FROM public.orders odd
LEFT JOIN public.accounts acc
	ON odd.account_id = acc.id 
LEFT JOIN public.sales_reps reps
	ON reps.id = acc.sales_rep_id
LEFT JOIN public.region reg
	ON reg.id = reps.region_id
GROUP BY region_name
ORDER BY average_order_value DESC 

-- 🔹 Conditional Aggregations (CASE + SUM)
/*
-- 16. What percentage of total revenue comes from:
	o standard paper?
	o poster paper?
	o glossy paper?
*/

SELECT 
	ROUND(SUM(standard_amt_usd) / SUM(total_amt_usd) * 100, 2) as std_paper_perecentage,
	ROUND(SUM(gloss_amt_usd) / SUM(total_amt_usd) * 100, 2) as gloss_paper_percentage,
	ROUND(SUM(poster_amt_usd) / SUM(total_amt_usd) * 100, 2) as post_paper_percentage
FROM public.orders  


-- 17. How many orders exceed $1,000?
SELECT 
	COUNT(total) as orders
FROM public.orders
WHERE total_amt_usd > 1000

-- 18. What is the total revenue from orders where total > 500 units?
SELECT 
	SUM(total_amt_usd) as total_revenue 
FROM public.orders
WHERE total > 500

-- 19. How many web events occurred per channel?
SELECT 
	web.channel channel_name,
	COUNT(channel) web_events_occured
FROM public.web_events web
GROUP BY channel_name
ORDER BY web_events_occured DESC

-- 20. Which web event channel generated the most activity?
SELECT 
	web.channel channel_name,
	COUNT(channel) web_events_occured
FROM public.web_events web
GROUP BY channel_name
ORDER BY web_events_occured DESC
LIMIT 1                                              -- Filter only channel with highest activity

-- 🔹 Advanced Aggregation & Business Analysis

-- 21. Which 5 accounts generated the highest total revenue?

-- (orders ➡️ accounts)
SELECT 
	acc.name account_name,
	SUM(total_amt_usd) total_revenue
FROM public.orders odd
LEFT JOIN public.accounts acc
ON acc.id = odd.account_id
GROUP BY account_name
ORDER BY total_revenue DESC                          -- Filter figures high - low
LIMIT 5                                              -- Filter only 5 accounts 

-- 22. Which region has the highest total revenue?

-- (orders ➡️ accounts ➡️ sales_reps ➡️ region)
SELECT 
	reg.name region_name,
	SUM(total_amt_usd) total_revenue
FROM public.orders odd 
LEFT JOIN public.accounts acc 
	ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps 
	ON reps.id = acc.sales_rep_id
LEFT JOIN public.region reg
	ON reg.id = reps.region_id
GROUP BY region_name
ORDER BY total_revenue DESC
LIMIT 1

-- 23. Rank sales reps by total revenue generated.

-- (orders ➡️ accounts ➡️ sales_reps)
SELECT 
	reps.name reps_names,
	SUM(total_amt_usd) total_revenue_generated
FROM public.orders odd 
LEFT JOIN public.accounts acc 
	ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps 
	ON reps.id = acc.sales_rep_id
GROUP BY reps_names
ORDER BY total_revenue_generated DESC 

-- 24. What is the total lifetime revenue per account?

-- (orders ➡️ accounts)
SELECT 
	acc.name account_name,
	SUM(total_amt_usd) as lifetime_revenue
FROM public.orders odd 
LEFT JOIN public.accounts acc 
	ON acc.id = odd.account_id
GROUP BY account_name

-- 25. What percentage of total company revenue does each region contribute?

-- %age total revenue = (region revenue/total revenue) * 100
SELECT
	reg.name region_name,
	ROUND(SUM(total_amt_usd) / (          -- computes region revenue 
	SELECT              
		SUM(total_amt_usd)                -- subquery calculates the total revenue across the entire company for use as comparison with region revenue 
	FROM public.orders) * 100, 2) perc_total_revenue           
FROM public.orders odd 
LEFT JOIN public.accounts acc 
	ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps 
	ON reps.id = acc.sales_rep_id
LEFT JOIN public.region reg 
	ON reg.id = reps.region_id            -- joins region with other tables to get region names
GROUP BY region_name
ORDER BY perc_total_revenue DESC

-- 26. What is the month-over-month revenue growth?

-- (orders ➡️ accounts ➡️ sales_reps ➡️ region)


-- 27. Compare the average revenue per order across regions.

-- (orders ➡️ accounts ➡️ sales_reps ➡️ region)
SELECT 
	public.region.name,
	ROUND(AVG(total_amt_usd), 2) as average_revenue
FROM public.orders
LEFT JOIN public.accounts
ON public.accounts.id = public.orders.account_id
LEFT JOIN public.sales_reps
ON public.sales_reps.id = public.accounts.sales_rep_id
LEFT JOIN public.region
ON public.region.id = public.sales_reps.region_id
GROUP BY public.region.name
ORDER BY average_revenue DESC

-- 28. Which accounts have never placed an order?
SELECT a.name account_name
FROM public.accounts a
WHERE NOT EXISTS
(SELECT 1
FROM public.orders o
WHERE o.account_id = a.id)

-- 29. For each account, compare the number of web events to the number of orders placed.

-- comparing orders count VS web events counts 
-- DISTINCT ensures you don’t double‑count the same record if it appears multiple times due to joins.
-- Use of ID avoids accidentally counting duplicates if joins create multiple rows.
SELECT 
	a.name account_name,                            -- retrives account names 
	COUNT(DISTINCT o.id) number_orders_placed,      -- retrives total orders placed per account
	COUNT(DISTINCT w.id) number_web_events          -- retrieves web events occured 
FROM public.orders o
LEFT JOIN public.accounts a
	ON a.id = o.account_id
LEFT JOIN public.web_events w
	ON w.account_id = a.id
GROUP BY account_name
ORDER BY account_name                               -- retieves accounts in their alphabetical order 

-- 30. For each account, what is the ratio of total revenue to total web events?

SELECT 
	a.name account_name,
	ROUND((SUM(o.total_amt_usd) / COUNT(w.occurred_at)), 2) tr_to_we_ratio   -- divide total revenue with total web events counts 
FROM public.orders o
LEFT JOIN public.accounts a
	ON a.id = o.account_id
LEFT JOIN public.web_events w
	ON w.account_id = a.id
GROUP BY account_name                                                          -- groups ratios by account names 

-- 🔹 Complex Analytical Questions

-- 31. What percentage of total revenue comes from the top 10% of customers?

-- we need to rank customers using NTILE window function 
-- create CTEs queries of two groups. Account revenues unit and ranked accounts unit. 
-- Main query = Account revenues / ranked accounts * 100 
WITH account_revenues AS (
	SELECT 
		a.name customers,
		a.id account_ids,
		SUM(total_amt_usd) total_revenue_per_acc
	FROM public.orders o
	LEFT JOIN public.accounts a 
			ON a.id = o.account_id
	GROUP BY account_ids, customers
),
ranked_accounts AS (
		SELECT
			customers,
			account_ids,
			total_revenue_per_acc,
			NTILE(10) OVER(ORDER BY total_revenue_per_acc DESC) ntile_range
		FROM account_revenues
)
SELECT 
	ROUND(SUM(CASE WHEN ntile_range = 1 THEN total_revenue_per_acc END)/SUM(total_revenue_per_acc) * 100, 2) top10_customer_revenue
FROM ranked_accounts

-- 32. For each region, which paper type generates the highest revenue?

WITH high_paper_revenue AS(
SELECT r.name region_name, SUM(o.standard_amt_usd) standard_paper, SUM(o.gloss_amt_usd) gloss_paper, SUM(o.poster_amt_usd) poster_paper
FROM public.orders o
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
LEFT JOIN public.region r ON r.id = sr.region_id
GROUP BY 1                                                         -- group paper type revenue by  region 
),
pivot AS(                                                          -- Convert paper types collumns to rows using UNION ALL
SELECT region_name, 'standard' paper_type, standard_paper revenue
FROM high_paper_revenue
UNION ALL 
SELECT region_name, 'gloss' paper_type, gloss_paper  revenue
FROM high_paper_revenue
UNION ALL 
SELECT region_name, 'poster' paper_type, poster_paper revenue  
FROM high_paper_revenue
),
ranked AS (                                                         -- rank paper types rows in descending order
SELECT region_name, paper_type, revenue, RANK() OVER(PARTITION BY region_name ORDER BY revenue DESC) highest_revenue
FROM pivot
)
SELECT region_name, paper_type, revenue 
FROM ranked
WHERE highest_revenue = 1                                           -- filter highest paper type revenue 

-- 33. Which sales rep has the highest average revenue per account?

WITH reps_avg AS (
SELECT sr.name rep_name, ROUND(AVG(total_amt_usd), 2) avg_revenue_per_acc
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
GROUP BY 1                                                              -- group reps according to their avg revenue 
), 
ranked_reps AS (                                                        -- rank reps with avg revenue 
SELECT rep_name, avg_revenue_per_acc, RANK() OVER(ORDER BY avg_revenue_per_acc DESC) high_avg_revenue
FROM reps_avg
)
SELECT rep_name, avg_revenue_per_acc
FROM ranked_reps
WHERE high_avg_revenue = 1                                               -- filter rep with highest avg revenue 

-- 34. Which month historically generates the highest revenue?

WITH time_line AS (
	SELECT                                                             --  extract months from timestamp 
		EXTRACT(year FROM occurred_at) years,
		EXTRACT(month FROM occurred_at) months,
		SUM(total_amt_usd) as total_revenue
	FROM public.orders
	GROUP BY 1, 2
),
ranked_months AS (                                                       -- rank months according to revenue generated 
	SELECT months, total_revenue, years, RANK() OVER(ORDER BY total_revenue DESC) final_revenue
	FROM time_line
)
SELECT years, months, total_revenue                                      -- filter columns interested in 
FROM ranked_months
WHERE final_revenue = 1                                                   -- filter to get highest revenue 

-- 35. What is the standard deviation of order values per region?

WITH region_values AS(
SELECT r.name region_name, total_amt_usd order_values 
FROM public.orders o
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
LEFT JOIN public.region r ON r.id = sr.region_id
GROUP BY 1, 2                                                     -- group order values with their respective regions 
)
SELECT region_name, ROUND(STDDEV(order_values), 2) std_deviation  -- compute standard deviation 
FROM region_values
GROUP BY 1                  
ORDER BY std_deviation DESC                                          















