-- PART 1: Subquery Questions (Non-CTE)

--  A. Scalar Subqueries

-- 1. Retrieve all orders where total_amt_usd is greater than the overall average order value.

SELECT *
FROM public.orders
WHERE total_amt_usd > (                                  -- filter orders with total_amt_usd > overall average order value.
SELECT ROUND(AVG(total_amt_usd), 2)
FROM public.orders
)

-- 2. Find accounts whose total revenue is greater than the average revenue per account.

SELECT   
	acc.id account_id,                                   -- select the account name
	acc.name account_name,
	SUM(total_amt_usd) total_revenue                     -- calculate total revenue per account
FROM public.orders odd
LEFT JOIN public.accounts acc
	ON acc.id = odd.account_id
GROUP BY 1, 2                                             -- group results followin order
HAVING SUM(total_amt_usd) > (                             -- Filter accounts whose total revenue is greater than AVG revenue
SELECT AVG(total_revenue)                                 --the average of all accounts total revenues
FROM (
	SELECT 	
		acc.id account_id,
		acc.name account_name,
		SUM(total_amt_usd) total_revenue                  -- calculate its total revenue
	FROM public.orders odd
	LEFT JOIN public.accounts acc
			ON acc.id = odd.account_id
	GROUP BY acc.id, account_name                         -- group by account to get per-account totals
	) sub                                                 -- name my subquery
)                                                         -- Outer query then compares each account’s total to this average

-- 3. Identify sales reps whose total revenue exceeds the average revenue generated by all sales reps.

-- SALES REP TOTAL REVENUE VS AVERAGE REVENUE OF ALL REPS 
SELECT 
	reps.name reps_names,
	SUM(total_amt_usd) total_revenue
FROM public.orders odd
LEFT JOIN public.accounts acc
	ON acc.id = odd.account_id
LEFT JOIN public.sales_reps reps
	ON reps.id = acc.sales_rep_id
GROUP BY 1
HAVING SUM(total_amt_usd) > ROUND((
SELECT AVG(total_revenue) average_revenue
FROM (
	SELECT 
		reps.name reps_names,
		SUM(total_amt_usd) total_revenue
	FROM public.orders odd
	LEFT JOIN public.accounts acc
		ON acc.id = odd.account_id
	LEFT JOIN public.sales_reps reps
		ON reps.id = acc.sales_rep_id
	GROUP BY reps_names
)
), 2)
ORDER BY total_revenue DESC

-- B. Correlated Subqueries

-- 4. Retrieve each account’s single largest order.

SELECT  
	acc.name account_name,                      -- retrievs the account names 
	total_amt_usd largest_order_amount          -- retrives largest single order amount 
FROM public.orders odd
LEFT JOIN public.accounts acc                   -- to retrive the account names from the table 
	ON acc.id = odd.account_id
WHERE (total_amt_usd) =(                        -- comparison bridge ensures we only keep the order that matches the largest one for that account 
	SELECT MAX(total_amt_usd) largest_order     -- retrives max order amount for the current account 
	FROM public.orders odd 
	WHERE odd.account_id = acc.id               -- ties the subquery to the outer query :correlation
)

-- OR 
SELECT * 
FROM orders o
WHERE total_amt_usd = (
    SELECT MAX(total_amt_usd)
    FROM orders
    WHERE account_id = o.account_id
);


-- 5. For each account, return its most recent order

SELECT 
	acc.name account_name,   
	odd.occurred_at date_time              -- retrieves order date/timestamp
FROM public.orders odd 
LEFT JOIN public.accounts acc 
	ON acc.id = odd.account_id             -- joins orders to accounts to show account names
WHERE odd.occurred_at = (                  -- keep only orders that match the most recent date
	SELECT MAX(occurred_at)                -- retrieves most recent order date for the current account 
	FROM public.orders odd
	WHERE odd.account_id = acc.id          -- ties subquery back to the outer query 
)

-- 6. For each region, return the account with the highest total revenue.

SELECT 
	reg.id,
	reg.name region_name, 
	acc.name account_name,
	SUM(total_amt_usd) total_revenue                                              -- computes total revenue per account from orders 
FROM public.orders odd
LEFT JOIN public.accounts acc ON acc.id = odd.account_id                          -- joins orders to accounts to get account names 
LEFT JOIN public.sales_reps reps ON reps.id = acc.sales_rep_id
LEFT JOIN public.region reg ON reg.id = reps.region_id                            -- joins regions to table to get region names 
GROUP BY 1, 2, 3                                                                  -- (ID)to tie together outer query & subquery.
HAVING SUM(total_amt_usd) = (                                                     -- filter to keep only the top account per region 
	SELECT MAX(account_total)                                                     -- find the maximum account total revenue in that region 
	FROM (
		SELECT 
			acc.id account_id, SUM(total_amt_usd) account_total            
		FROM public.orders odd
		LEFT JOIN public.accounts acc ON acc.id = odd.account_id                  
		LEFT JOIN public.sales_reps reps ON reps.id = acc.sales_rep_id
		LEFT JOIN public.region rg ON rg.id = reps.region_id     
		WHERE rg.id = reg.id                                                      -- ties the subquery back to the outer
		GROUP BY acc.id                                                           -- compute totals per account
		) sub_query
)
ORDER BY region_name, total_revenue DESC                                          --  order the results for readability


-- 7. Provide the name of the sales_rep in each region with the largest amount of total_amt_usd sales.

WITH sales_rep_revenue AS (
SELECT sr.name sales_rep_name, r.name region_name, sr.id, SUM(total_amt_usd) total_revenue
FROM public.region r
LEFT JOIN public.sales_reps sr ON r.id = sr.region_id
LEFT JOIN public.accounts a ON a.sales_rep_id = sr.id
LEFT JOIN public.orders o ON o.account_id = a.id
GROUP BY 1, 2, 3
),
ranked_reps AS (
SELECT *, RANK() OVER(partition by region_name order by total_revenue DESC) region_rank
FROM sales_rep_revenue
)
SELECT region_name, sales_rep_name, total_revenue 
FROM ranked_reps
WHERE region_rank = 1
ORDER BY 1

-- 8. For the region with the largest (sum) of sales total_amt_usd, how many total (count) orders were placed? 

-- CTE 1 (region_revenue) → Calculate total revenue per region.
-- CTE 2 (top_region) → Pick the region with the highest revenue.
-- Outer query → Count orders, but only for that region (WHERE region_id = top_region).
WITH region_revenue AS (
SELECT 
	r.id region_id,
	r.name region_name,
	SUM(total_amt_usd) total_revenue
FROM public.orders o
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id 
LEFT JOIN public.region r ON r.id = sr.region_id
GROUP BY 1,2
), 
top_region AS (
SELECT region_id, region_name
FROM region_revenue
ORDER BY total_revenue DESC
LIMIT 1
)
SELECT COUNT(o.id) 
FROM public.orders o
LEFT JOIN public.accounts a  ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
WHERE (SELECT region_id FROM top_region) = sr.region_id

-- 9. How many accounts had more total purchases than the account name which has bought the most standard_qty paper throughout their lifetime as a customer?
-- Step 1: Compute each account’s total purchases.
-- Step 2: Compute the account that bought the most standard_qty paper.
-- Step 3: Compare all accounts total purchases against that account’s purchases.

WITH account_total_purchases AS (                      -- compute total money spent per account
SELECT a.id account_id, a.name account_name, SUM(total_amt_usd) total_purchases 
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
GROUP BY 1, 2                                       
),
standard_qty AS (                                      -- computing account with most standard quantity paper
SELECT a.id account_idr, a.name account_name, SUM(standard_qty) total_standard_qty
FROM public.orders o 
LEFT JOIN public.accounts a  ON a.id = o.account_id
GROUP BY 1
ORDER BY total_standard_qty DESC
LIMIT 1                                        
)
SELECT COUNT(*)                                     -- finds the total purchases of the account that bought the most standard_qty paper
FROM account_total_purchases
WHERE total_purchases > (
SELECT total_standard_qty                           --finds the total purchases of the account that bought the most standard_qty paper.
FROM standard_qty
WHERE account_id = (SELECT account_idr FROM standard_qty)             
)           -- This identifies the account ID of the “standard_qty leader” (account with highest lifetime standard_qty purchases).

-- 10. For the customer that spent the most (in total over their lifetime as a customer) total_amt_usd, how many web_events did they have for each channel?

WITH lifetime_spend AS(
SELECT a.name account_name, a.id account_id, SUM(total_amt_usd) total_spent 
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id 
GROUP BY 1, 2                                                                  -- compute total_amt_usd group by customer
), 
highest_spender AS (
SELECT account_name, account_id
FROM lifetime_spend
ORDER BY total_spent DESC 
LIMIT 1                                                                        -- compute highest customer to ever spend 
)
SELECT w.channel, COUNT(*) web_event_count
FROM public.web_events w
LEFT JOIN public.accounts a ON a.id = w.account_id
WHERE w.account_id = (SELECT account_id FROM highest_spender)
GROUP BY 1
ORDER BY web_event_count DESC                                                  -- count web events per channel 

-- 11. What is the lifetime average amount spent in terms of total_amt_usd for the top 10 total spending accounts?

WITH total_spending AS(
SELECT a.id account_id, a.name account_name, SUM(total_amt_usd) total_spending
FROM public.orders o
LEFT JOIN public.accounts a ON a.id = o.account_id
GROUP BY 1, 2                                                                   -- Compute total spending per account.
), 
top_ten_accounts AS (
SELECT *
FROM total_spending
ORDER BY total_spending DESC
LIMIT 10                                                                        -- Filter top 10 accounts by total spending.
)                                                              
SELECT account_name, ROUND(AVG(total_spending), 2) lifetime_avg_amount
FROM top_ten_accounts
GROUP BY 1                                                                     -- Compute average total spending across the top 10 accounts.

-- 12. What is the lifetime average amount spent in terms of total_amt_usd, including only the companies that spent more per order, on average, than the average of all orders.

WITH total_spent AS (
SELECT  a.id account_id, a.name account_name, ROUND(AVG(total_amt_usd), 2) average_spent
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id 
GROUP BY 1, 2                                                 -- compute overall average of all orders 
), 
filtered_cos AS (
SELECT *
FROM total_spent
WHERE average_spent > (                                       -- filter companies that spent more per order than average
SELECT AVG(average_spent)
FROM total_spent
))
SELECT ROUND(AVG(average_spent), 2) filtered_cos_avg
FROM filtered_cos                                              -- retrive average amount spent (total_amt_usd)

-- KEY TAKEAWAYS
-- Outer vs. subquery: outer computes totals, subquery finds the max.
-- Use IDs: always group by IDs for uniqueness.
-- Correlation: every correlated subquery needs a WHERE tie‑back to the outer query.

-- C. IN / EXISTS Subqueries

-- 7. Retrieve accounts that have placed at least one order (use EXISTS).
  
SELECT a.name                         -- retrives names of the accounts 
FROM public.accounts a
WHERE EXISTS                          -- filter to keep only accounts that have at least one order
(SELECT 1                             -- returns a dummy value if a match exists  (Interested in existence & not results)
FROM public.orders o   
WHERE a.id = o.account_id)            -- tie back the subquery to the outer query

-- 8. Retrieve accounts that have never placed an order (use NOT EXISTS).

SELECT a.name                         
FROM public.accounts a
WHERE NOT EXISTS                          
(SELECT 1                           
FROM public.orders o   
WHERE a.id = o.account_id)   

-- 9. Find sales reps who have handled at least one order above $5,000.

SELECT r.name                        -- selects the sales rep’s name
FROM public.sales_reps r 
LEFT JOIN public.accounts a          -- joins accounts to sales reps
	ON a.sales_rep_id = r.id
WHERE EXISTS                         -- filter sales reps who have at least one qualifying order
(SELECT 1                            -- subquery returns a dummy value if a match exists
FROM  public.orders o
WHERE o.account_id = a.id            -- tie back subquery to main query
AND total_amt_usd > 5000)            -- condition to retain only orders above $5000


-- D Subqueries in FROM Clause (Derived Tables)

-- 10. Create a subquery that calculates total revenue per account, then: Return only those accounts where revenue > 100,000.

WITH total_acc_revenue AS (
SELECT a.name account_name, SUM(total_amt_usd) account_revenue
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
GROUP BY 1
)
SELECT *
FROM total_acc_revenue
WHERE account_revenue > 100000

-- 11. Build a subquery that calculates revenue per region. In the outer query, return the region with the maximum revenue

WITH region_revenue AS (
SELECT r.name region_name, SUM(total_amt_usd) region_revenue
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
LEFT JOIN public.region r ON r.id = sr.region_id 
GROUP BY 1
)
SELECT *
FROM region_revenue
ORDER BY 2 DESC
LIMIT 1 

-- PART 2: CTE (Common Table Expression) Questions

-- A. Basic CTE 

-- 12. Create a CTE that calculates total revenue per account. Use it to return the top 10 accounts by revenue.
WITH total_revenue_per_acc AS (
SELECT a.name account_name, SUM(total_amt_usd) account_revenue
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
GROUP BY 1
)
SELECT *
FROM total_revenue_per_acc
ORDER BY 2 DESC
LIMIT 10

-- 13. Use a CTE to calculate total orders handled by each sales rep. Return only those with more than 100 orders.

WITH reps_orders AS (
SELECT sr.name reps_names, SUM(total) reps_total_orders
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id 
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
GROUP BY 1
)
SELECT *
FROM reps_orders
WHERE reps_total_orders > 100000

--  B. Multi-CTE Queries

-- 14. Compare Region Revenue to Company Average
-- • CTE 1: Calculate revenue per region.
-- • CTE 2: Calculate overall average region revenue.
-- • Final query: Show regions performing above average.
WITH region_per_revenue AS (
SELECT r.id region_id, r.name region_name, SUM(total_amt_usd) region_revenue
FROM public.orders o 
LEFT JOIN public.accounts a ON a.id = o.account_id
LEFT JOIN public.sales_reps sr ON sr.id = a.sales_rep_id
LEFT JOIN public.region r ON r.id = sr.region_id 
GROUP BY 1, 2
),
average_region_revenue AS (
SELECT AVG(region_revenue) average_revenue_per_region
FROM region_per_revenue
)
SELECT rr.region_id, rr.region_name, rr.region_revenue
FROM region_per_revenue rr
CROSS JOIN average_region_revenue ar
WHERE rr.region_revenue > ar.average_revenue_per_region
ORDER BY region_revenue DESC
















